import { Product, Testimonial, BlogPost } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Lundmy Blazer',
    price: 7200,
    category: 'men',
    subCategory: 'Jackets',
    images: ['https://images.unsplash.com/photo-1594932224828-b4b057b7d6ee?q=80&w=800&auto=format&fit=crop'],
    description: 'Premium wool blend blazer for a sharp look.',
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    trending: true,
  },
  {
    id: '2',
    name: 'Fobr Day Top',
    price: 4500,
    category: 'women',
    subCategory: 'Tops',
    images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop'],
    description: 'Elegant silk top for everyday luxury.',
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    trending: true,
  },
  {
    id: '3',
    name: 'Restchphild Coat',
    price: 17000,
    category: 'women',
    subCategory: 'Outerwear',
    images: ['https://images.unsplash.com/photo-1539533377285-a9218d60c30c?q=80&w=800&auto=format&fit=crop'],
    description: 'Classic camel coat for the Nairobi cool evenings.',
    sizes: ['S', 'M', 'L'],
    inStock: true,
    trending: true,
  },
  {
    id: '4',
    name: 'Recloder Sitent Dress',
    price: 8900,
    category: 'women',
    subCategory: 'Dresses',
    images: ['https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=800&auto=format&fit=crop'],
    description: 'Sophisticated midi dress for any occasion.',
    sizes: ['S', 'M', 'L'],
    inStock: true,
    trending: true,
  },
  {
    id: '5',
    name: 'Kids Denim Jacket',
    price: 3200,
    category: 'kids',
    subCategory: 'Jackets',
    images: ['https://images.unsplash.com/photo-1519457431-7571f018272b?q=80&w=800&auto=format&fit=crop'],
    description: 'Durable and stylish denim for active kids.',
    sizes: ['2Y', '4Y', '6Y', '8Y'],
    inStock: true,
    isNew: true,
  },
  {
    id: '6',
    name: 'Floral Maxi Dress',
    price: 5500,
    category: 'women',
    subCategory: 'Dresses',
    images: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=800&auto=format&fit=crop'],
    description: 'Beautiful floral print maxi dress.',
    sizes: ['S', 'M', 'L'],
    inStock: true,
    isSale: true,
    salePrice: 3900,
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah W.',
    location: 'Kilimani, Nairobi',
    content: 'The delivery was so fast! Ordered in the morning and got it by 4 PM. The quality is amazing.',
    rating: 5,
  },
  {
    id: '2',
    name: 'John K.',
    location: 'Westlands, Nairobi',
    content: 'Finally a store that gets M-Pesa right. Seamless checkout and great customer service.',
    rating: 5,
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'Best Dresses in Nairobi 2025',
    excerpt: 'Discover the trending styles that are taking over the streets of Nairobi this year.',
    content: 'Full content here...',
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=800&auto=format&fit=crop',
    date: '2025-04-10',
    slug: 'best-dresses-nairobi-2025',
  },
  {
    id: '2',
    title: 'Affordable Men’s Fashion in Nairobi',
    excerpt: 'How to look sharp without breaking the bank. Our top picks for the modern man.',
    content: 'Full content here...',
    image: 'https://images.unsplash.com/photo-1488161628813-04466f872be2?q=80&w=800&auto=format&fit=crop',
    date: '2025-04-12',
    slug: 'affordable-mens-fashion',
  },
];
